### ISSUE TITLE
Command arguments

### ISSUE THREAD

**Issue by HideakiAtsuyo** [luccanunes/discord.cpp#7]
How can i add an argument?

Example:
*command theargument | or | *command multiples argument

**Comment by luccanunes** [comment]
I don't fully understand what you mean, could you elaborate?

**Comment by HideakiAtsuyo** [comment]
Basic command:

PrefixCommand:

*say

Now the needed argument:

*say here a thing

The bot need to send: here a thing

**Comment by luccanunes** [comment]
For now, since there's no `Command` class yet, you'll have to manually manipulate the string.
You could use something like [strim](https://github.com/luccanunes/strim) (another library of mine, still undocumented), to split `message.content` by a space(" ") into an `std::vector<std::string>` with each individual word.

here's a quick example:
```cpp
#include <dpp.h>
#include <strim.h>
#include <iostream>

int main
{
  dpp::Client client;
  client.onReady([&]() {
    std::cout << "logged in\n";
  });
  client.onMessage([&]() {
    if (message.startsWith(prefix + "say") {
      const std::vector<std::string> args = strim::split(message.content, " "); // returns something like {"-say", "here", "a", "thing"}
      std::string response = "";
      for (int i = 1; i < args.size(); i++)  response += args[i] + " ";
      message.reply(response);
    }
  });

  return 0;
}
```

**Comment by HideakiAtsuyo** [comment]
Oof ok thanks
