### ISSUE TITLE
client.run needs token validation

### ISSUE THREAD

**Issue by HideakiAtsuyo** [luccanunes/discord.cpp#8]
https://i.imgur.com/1vUTNFl.png

Need to add a verification i think in [Client.cpp](https://github.com/luccanunes/discord.cpp/blob/main/src/Client.cpp) :)

**Comment by luccanunes** [comment]
Could you tell me what steps you made so I can try and reproduce them?

**Comment by HideakiAtsuyo** [comment]
Just:


```c++
try{
client.run("the token");
} catch (std::string e){
std::cout << "Invalid token" ;
}
```
In normal time (in discord.js i don't know for discord.py) but it it's supposed to tell me `Invalid token`

**Comment by luccanunes** [comment]
Seems to be fixed in the latest commits, please pull them to your local repo, test them, and give me some feedback
In case your curious:
When the token is invalid, the discord gateway returns a 4004 error code and finishs the connection, since we wasn't handling that at all, the default behavior of `IXWebSocket`, the library we use for websockets, is to try and connect again.

Now, when such code is received, `client` throws a `std::invalid_argument` exception.

**Comment by HideakiAtsuyo** [comment]
Nice
